version: '3.8'

services:
  app:
    build: .
    container_name: cosmic_horoscopes
    restart: always
    ports:
      - "80:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/sqlite.db
